config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  validates :content, presence: true
end

app/models/quantity_ingredient.rb
class QuantityIngredient < ApplicationRecord
  belongs_to :recipe
  validates :quantities_and_ingredients, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :stars, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :creator, class_name: :User, foreign_key: "creator_id"
  belongs_to :poster, class_name: :User, foreign_key: "poster_id"
  has_many :quantity_ingredients
  has_many :comments
  has_many :users, through: :comments
  has_many :ratings
  has_many :users, through: :ratings
  has_many :saved_recipes
  has_many :users, through: :saved_recipes


  validates :name, presence: true
  validates :category, presence: true, inclusion: { in: ["Entrée / Apéro", "Plat principal végétarien", "Plat principal à base de viande", "Plat principal à base de poisson", "Dessert"] }
  validates :cooktime, inclusion: { in: [0, 5, 10, 15, 20, 25, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 240, 300, 360, 420] }
  validates :preptime, inclusion: { in: [0, 5, 10, 15, 20, 25, 30, 45, 60, 75, 90] }
  validates :creator_id, presence: true
  validates :poster_id, presence: true
end

app/models/saved_recipe.rb
class SavedRecipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :created_recipes, class_name: :Recipe, foreign_key: "creator_id"
  has_many :posted_recipes, class_name: :Recipe, foreign_key: "poster_id"

  has_many :comments
  has_many :saved_recipes
  has_many :rating

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @latest_recipes = Recipe.order(created_at: :desc).limit(3)

    @random_starter = Recipe.where(category: "Entrée / Apéro").limit(1).order("RANDOM()").first

    random_main_category = ["Plat principal végétarien", "Plat principal à base de viande", "Plat principal à base de poisson"].sample
    @random_main = Recipe.where(category: random_main_category).limit(1).order("RANDOM()").first

    @random_desert = Recipe.where(category: "Dessert").limit(1).order("RANDOM()").first
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_recipe, only: [:show]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 30%, rgba(0,0,0,0.5) 50%), url(<%= image_path "daube-sanglier.jpg" %>);""">
  <div class="container">
    <div class="wrapper-center">
      <h1>Nos recettes de famille</h1>
      <input type="text" placeholder="Entrez une recette, un ingrédient, un utilisateur...">
      <%= link_to "Voir toutes les recettes", recipes_path %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <h2>Dernières recettes ajoutées</h2>
  </div>
  <div class="row">
    <div class="card-deck">
      <% @latest_recipes.each do |recipe| %>
        <div class="card">
          <%= link_to recipe_path(recipe) do %>
            <%= image_tag "placeholder", alt: "alttext", class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title"><%= recipe.name %></h5>
              <h6 class="card-title"><%= recipe.category %></h6>
              <p class="card-text"><%= recipe.creator.first_name %></p>
            </div>
            <div class="card-footer">
              <small class="text-muted">Last updated 3 mins ago</small>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <h2>Un repas complet au hasard pour la 2!</h2>
  </div>
  <div class="row">
    <div class="card-deck">
      <div class="card">
        <%= link_to recipe_path(@random_starter.id) do %>
          <%= image_tag "placeholder", alt: "alttext", class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= @random_starter.name %> - <%= @random_starter.category %></h5>
            <p class="card-text"><%= @random_starter.creator.first_name %></p>
          </div>
        <% end %>
      </div>
      <div class="card">
        <%= link_to recipe_path(@random_main.id) do %>
          <%= image_tag "placeholder", alt: "alttext", class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= @random_main.name %> - <%= @random_main.category %></h5>
            <p class="card-text"><%= @random_main.creator.first_name %></p>
          </div>
        <% end %>
      </div>
      <div class="card">
        <%= link_to recipe_path(@random_desert.id) do %>
          <%= image_tag "placeholder", alt: "alttext", class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= @random_desert.name %> - <%= @random_desert.category %></h5>
            <p class="card-text"><%= @random_desert.creator.first_name %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <h1>Toutes les recettes</h1>
  <div class="row">
    <h2>Dernières recettes ajoutées</h2>
  </div>
  <div class="row">
    <% @recipes.each do |recipe| %>
      <%= link_to recipe_path(recipe) do %>
        <div class="card mb-3">
          <div class="row no-gutters">
            <div class="col-md-4">
              <%= image_tag "placeholder", alt: "alttext", class: "card-img" %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><%= recipe.name %> - <%= recipe.category %> de <%= recipe.creator.first_name %></h5>
                <p class="card-text"><%= recipe.description.truncate(150) %></p>
                <p class="card-text"><small class="text-muted">Créé le <%= recipe.created_at %></small></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <h1><%= @recipe.name %></h1>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <%= "****" %> - <%= pluralize(@recipe.comments.count, "comment")%>
      <%= image_tag "placeholder", alt: "alttext", class: "card-img-top" %>
    </div>
    <div class="col-xs-12 col-md-4">
      <h2>Ingredients</h2>
      <ul>
        <% @recipe.quantity_ingredients.each do |qandi| %>
          <li><%= qandi.quantities_and_ingredients %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <h2>Préparation</h2>
      <p><%= @recipe.description %></p>
    </div>
    <div class="col-xs-12 col-md-4">
      <h2>Commentaires</h2>
<!--         <ul>
 -->          <% @recipe.comments.each do |comment| %>
<!--             <li> -->
              <div class="row">
                <div class="col-2 col-xs-2">
                  <%= image_tag "default-profile", alt: "alttext", class: "img-fluid avatar" %>
                </div>
                <div class="col-10 col-xs-10">
                  <%= Rating.where %>
                  <%= comment.content %> from <%= comment.user.first_name %></li>
                </div>
              </div>
<!--             </li>
 -->          <% end %>
<!--         </ul>
 -->    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>